#!/usr/bin/env bash
# DigiTracker — write runtime secrets onto the server from the CI environment.
#
# Called by .github/workflows/deploy.yml as the FIRST step after checkout, with
# GitHub Actions secrets exported as environment variables. Nothing here is ever
# committed to git. If a required secret is missing the script fails before any
# file is touched, so the deploy aborts and the currently running app is left
# exactly as it was.
#
# Output: /etc/digitracker/digitracker.env  (root:www-data, mode 0640)
#   KEY='value' lines — sourced by scripts/*.sh and parsed by config.php.
#   Readable by root (systemd scripts, certbot renewal) and www-data (PHP).
set -euo pipefail

ENV_DIR="/etc/digitracker"
ENV_FILE="$ENV_DIR/digitracker.env"

REQUIRED=(DB_PASS)
OPTIONAL=(DB_HOST DB_NAME DB_USER
          GMAIL_CLIENT_ID GMAIL_CLIENT_SECRET GMAIL_REDIRECT_URI
          DUCKDNS_TOKEN DUCKDNS_DOMAIN)

missing=()
for k in "${REQUIRED[@]}"; do [ -n "${!k:-}" ] || missing+=("$k"); done
if [ ${#missing[@]} -gt 0 ]; then
  echo "[FAIL] Required secret(s) not set: ${missing[*]}"
  echo "       Add them under GitHub → Settings → Secrets and variables → Actions,"
  echo "       then re-run the deploy. Aborting before any files are touched."
  exit 1
fi

TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

{
  echo "# Generated by scripts/write-secrets.sh from GitHub Actions secrets — do not edit by hand."
  echo "# Written $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
  for k in "${REQUIRED[@]}" "${OPTIONAL[@]}"; do
    v="${!k:-}"
    [ -n "$v" ] || continue
    # Single-quoted so bash can source any value verbatim; a value containing a
    # single quote or newline can't be represented, so refuse it loudly.
    if [[ "$v" == *"'"* || "$v" == *$'\n'* ]]; then
      echo "[FAIL] Secret $k contains a single quote or newline, which this file format cannot carry." >&2
      exit 1
    fi
    printf "%s='%s'\n" "$k" "$v"
  done
} > "$TMP"

sudo mkdir -p "$ENV_DIR"
sudo cp "$TMP" "$ENV_FILE"
sudo chown root:www-data "$ENV_FILE"
sudo chmod 640 "$ENV_FILE"
echo "[OK] Wrote $ENV_FILE ($(grep -c "='" "$TMP") keys)"
